collections:
  categories:
    output: true
  categoriesCR:
    output: true
  codes:
    output: true  

defaults:
  - scope:
      path: 
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: 
      type: "posts"
    values:
      layout: "post"
  - scope:
      path:
      type: "categories"
    values:
      layout: category
  - scope:
      path:
      type: "categoriesCR"
    values:
      layout: categoryCR
  - scope:
      path: 
    values:
      layout: "default"