collections:
  codes:
    output: true  

defaults:
  - scope:
      path: 
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: 
      type: "posts"
    values:
      layout: "post"
  - scope:
      path:
      type: "codes"
    values:
      layout: postCR
  - scope:
      path: 
    values:
      layout: "default"


data_output:
  - name: categories
    options:
      - path: categories
        name_from: key
        values:
          layout: category
        dynamic_values:
          category_key: key
      - path: categoriesCR
        name_from: key
        values:
          layout: categoryCR
        dynamic_values:
          category_key: key